### PR TITLE
feat: add Stable token factory

### PR DESCRIPTION
**Pull request by johnletey**

### CODE REVIEW

**Review by boojamya — COMMENTED** [review]
Hey John, it's lookin good!

Any reason you got rid of all the previous app/upgrades folders? Or just a cleanup?

ALSO,
We will want to add the new stabletokenfactory to the `OnRecPacket` in the blockibc middleware.

**Comment by johnletey** [comment]
Thanks for the review @boojamya 🔥 

> Any reason you got rid of all the previous app/upgrades folders? Or just a cleanup?

This is strictly a cleanup.

> We will want to add the new stabletokenfactory to the OnRecPacket in the blockibc middleware.

Very nice catch! Made this change in https://github.com/strangelove-ventures/noble/pull/269/commits/ab3b6ff9e6ff069980fc475ee17e03b3dd6fe45f, feel free to check it out!

I also have one more change coming, which allows the `x/tariff` module to have multiple different fee denoms (right now it only supports one, namely `uusdc`).

**Review by boojamya — APPROVED** [review]
Nice work. Looks good!

**Comment by johnletey** [comment]
@Mergifyio backport release/v4.1.x

**Pull request merged**
